godzilla-la-leyenda/godzillaLaLeyenda/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

godzilla-la-leyenda/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name="index"),
    path('add_movie/', views.add_movie, name="add_movie"),
    path('upload_movie/', views.upload_movie, name="upload_movie")
]

godzilla-la-leyenda/movies/models.py
from django.db import models


class Movie(models.Model):
    title_movie = models.CharField(max_length=100)
    poster = models.ImageField('Imagen', upload_to='posters/', max_length=255)
    description_text = models.CharField(max_length=300)
    duration = models.CharField(max_length=50)
    download = models.CharField(max_length=150)


    def  __str__(self):
        return self.title_movie

godzilla-la-leyenda/movies/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Movie


def index(request):
    latest_movie_list = Movie.objects.all()
    return render(request, 'movies/index.html', {
        'latest_movie_list': latest_movie_list
    })

def add_movie(request):
    return render(request, 'movies/Agregar_pelicula.html')


def upload_movie(request):

    return redirect(request, 'movies/index.html') 

godzilla-la-leyenda/movies/templates/movies/Agregar_pelicula.html
{% extends './base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'movies:upload_movie' %}" method="post">
{% csrf_token %}
    <section class="form-register">
        <label for="titulo">Titulo:</label>
        <input class="controls" type="text" name="titulo" id="titulo">
    
        <label for="poster">Poster:</label>
        <input type="file" name="poster" id="poster">
    
        <label for="descripcion">Descripcion:</label>
        <input class="controls" type="text" name="descripcion" id="descripcion">
    
        <label for="duracion">duracion:</label>
        <input class="controls" type="text" name="duracion" id="duracion">
    
        <label for="descargar">Descarga:</label>
        <input class="controls" type="text" name="descargar" id="descargar">
    
        <input class="botons" type="submit" value="Subir">
    </section>
</form>
{% endblock  %}

godzilla-la-leyenda/movies/templates/movies/Godzilla descarga.html
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Godzilla la leyenda</title>
		<link rel="stylesheet" href="Zilla.css">
</head>
<body>
<div id="Agrupar">	
	<header id="Cabecera">
			<hgroup>
					<h1 id="Titulo">Godzilla la leyenda</h1>
					<h2>Subtitulo principal</h2>
			</hgroup>
	</header>
		<nav id="Menu">
				<ul>
					<li><a href="Godzilla la leyenda.html">Inicio</a></li>
					<li><a href="Godzilla descarga.html">Descarga</a></li>
					<li><a href="">Contactos</a></li>
					<li><a href="">Ayuda</a></li>
				</ul>
		</nav>
			<section id="Seccion">
			
			</section>
				<aside id="Columna">
						<blockquote>Mensaje 1</blockquote>
						<blockquote>Mensaje 2</blockquote>
				</aside>
					<footer id="Pie">
						<span>La toho me va a romper el orto con los derechos</span>
					</footer>
</div>
</body>
</html>

godzilla-la-leyenda/movies/templates/movies/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Godzilla la leyenda</title>
	<link rel="stylesheet" href="{% static 'css/zilla.css' %}">
</head>
<body>
<div id="Agrupar">	
	<header id="Cabecera" style= "background-image: url({% static 'img/Godzilla-2014.jpg' %});">
			<hgroup>
					<h1 id="Titulo">Godzilla la leyenda</h1>
					<h2>Subtitulo principal</h2>
			</hgroup>
	</header>
		<nav id="Menu">
				<ul>
					<li><a href="">Inicio</a></li>
					<li><a href="">Descarga</a></li>
					<li><a href="">Contactos</a></li>
					<li><a href="">Ayuda</a></li>
				</ul>
		</nav>
			<section id="Seccion">
				{% block content %}
                
                {% endblock %}
			</section>
				<aside id="Columna">
						<blockquote>Mensaje 1</blockquote>
						<blockquote>Mensaje 2</blockquote>
				</aside>
					<footer id="Pie">
						<span>La toho me va a romper el orto con los derechos</span>
					</footer>
</div>
</body>
</html>

godzilla-la-leyenda/movies/templates/movies/index.html
{% extends './base.html' %}
{% load static %}
{% block content %}
{% if latest_movie_list %}
<article class="publicacion">
	{% for movie in latest_movie_list %}
		<header>
			<h1>{{ movie.title_movie }}</h1>
		</header>
		<figure id="poster">
			<img src={% static 'img/poster 1.t.jpg' %} id="poster">
			<figcaption id="text_movie">
				<p>{{ movie.description_text }}</p>
				<span>duracion: {{movie.duration}}</span>
				<a href={{ movie.download }}><span>descargar aqui</span></a>
			</figcaption>
		</figure>
	{% endfor %}
</article>
{% else %}
<p>No movies availables.</p>
{% endif %}
{% endblock  %}

godzilla-la-leyenda/movies/templates/movies/plantilla.html
<article class= "publicacion">
    <header>
        <hgroup>
            <h1>Godzilla(1954)</h1>
        </hgroup>
    </header>
            <figure>
                <img src= {% static 'img/poster 1.t.jpg' %}>
                <figcaption><p>Un gigante monstruo lanzallamas aterroriza a Japón<br> después de que una bomba atómica lo despierta <br>luego de estar dormido durante varios siglos.</p></figcaption>
            </figure>
</article>
<article>
    <header>
        <hgroup>
            <h1>Godzilla Raids Again(1955)</h1>
        </hgroup>
    </header>
            <figure>
                <img src= {% static 'img/poster 2.t.jpg' %}>
                <figcaption><p>Un gigante monstruo lanzallamas aterroriza a Japón<br> después de que una bomba atómica lo despierta <br>luego de estar dormido durante varios siglos.</p></figcaption>
</article>
<article>
    <header>
        <hgroup>
            <h1>King Kong vs. Godzilla(1962)</h1>
        </hgroup>
    </header>
            <figure>
                <img src= {% static 'img/poster 3.t.jpg' %}>
                <figcaption><p>Un gigante monstruo lanzallamas aterroriza a Japón<br> después de que una bomba atómica lo despierta <br>luego de estar dormido durante varios siglos.</p></figcaption>
</article>